[dx]
port = 3001
[server]
host = 'localhost:3000'
[redpanda]
admin = 'localhost:18082'

[[webhooks.ai.greet]]
enable = true
endpoint = "http://localhost:3000/debug/render/layout.json"
accept = "application/json"

[[webhooks.ai.greet]]
enable = true
path = "user.json"

[[webhooks.ai.greet]]
enable = true
path = "segment.tmpl.json"
