logic = 'chat' # chat, crm, echo

[trace]
format = 'compact'

[queue.outgo]
type = 'kafka'
broker = ['localhost:19092']
topic = 'push'

[queue.income]
type = 'kafka'
broker = ['localhost:19092']
topic = ['event']
group = 'chat'

[database]
type = 'postgres'
host = 'localhost'
port = 15432
db = 'chat'
user = 'chat'
passwd = 'chat'


[gateway]
base_url = "http://localhost:3000/config/hooks/"

[hooks.login]
endpoint = "http://localhost:3003/v1/login?layout=true"
accept = "application/json"

[hooks.logout]
endpoint = "http://localhost:3003/v1/logout?layout=true"
accept = "application/json"

[[hooks.greet]]
path = "segment.tmpl.json"

[[hooks.greet]]
endpoint = "http://localhost:3003/v1/yaml/chat_layout.yaml"
accept = "application/json"

[[hooks.greet]]
disable = true
path = "user.json"

# channel::list
[[hooks.greet]]
disable = false
endpoint = "http://localhost:3003/v1/channel?layout=true"
accept = "application/json"

[[hooks.greet]]
disable = true
endpoint = "http://localhost:3003/v1/history?layout=true"
accept = "application/json"

[[hooks."channel::join"]]
disable = true
endpoint = "http://localhost:3003/v1/channel?layout=true"
accept = "application/json"

[[hooks."channel::select"]]
endpoint = "http://localhost:3003/v1/channel/select?layout=true"
accept = "application/json"
