logic = 'chat' # chat, crm, echo

[trace]
format = 'compact'

[queue]
enable = true

[queue.outgo]
type = 'kafka'
broker = ['localhost:19092']
topic = 'push'

[queue.income]
type = 'kafka'
broker = ['localhost:19092']
topic = ['event']
group = 'chat'

[database]
type = 'postgres'
host = 'localhost'
port = 15432
db = 'chat'
user = 'chat'
passwd = 'chat'


[gateway]
url = "http://localhost:3000/config/hooks/greet"

[login]
enable = true
endpoint = "http://localhost:3003/v1/login"
accept = "application/json"

[logout]
enable = true
endpoint = "http://localhost:3003/v1/logout"
accept = "application/json"

[[greet]]
enable = true
endpoint = "http://localhost:3000/debug/render/layout.json"
accept = "application/json"

[[greet]]
enable = true
path = "user.json"

[[greet]]
enable = true
path = "segment.tmpl.json"
