logic = 'chat' # chat, crm, echo

[trace]
format = 'compact'

[queue.outgo]
type = 'kafka'
broker = ['localhost:19092']
topic = 'push'

[queue.income]
type = 'kafka'
broker = ['localhost:19092']
topic = ['event']
group = 'chat'

[database]
type = 'postgres'
host = 'localhost'
port = 15432
db = 'chat'
user = 'chat'
passwd = 'chat'


[gateway]
base_url = "http://localhost:3000/config/hooks/"

[login]
endpoint = "http://localhost:3003/v1/login?layout=true"
accept = "application/json"

[logout]
endpoint = "http://localhost:3003/v1/logout?layout=true"
accept = "application/json"

[[greet]]
endpoint = "http://localhost:3000/debug/render/layout.json"
accept = "application/json"

[[greet]]
path = "user.json"

[[greet]]
disable = false
endpoint = "http://localhost:3003/v1/channel?layout=true"
accept = "application/json"

[[greet]]
disable = false
endpoint = "http://localhost:3003/v1/history?layout=true"
accept = "application/json"

[[greet]]
path = "segment.tmpl.json"
