logic = 'chat'

[trace]
format = 'compact'

[queue]
enable = true

[queue.outgo]
type = 'kafka'
broker = ['localhost:19092']
topic = 'push'

[queue.income]
type = 'kafka'
broker = ['localhost:19092']
topic = ['event']
group = 'chat'

[database]
type = 'postgres'
host = 'localhost'
port = 15432
db = 'chat'
user = 'chat'
passwd = 'chat'
