[trace]
format = 'compact'

[queue]
enable = true

[queue.outgo]
type = 'kafka'
broker = ['localhost:19092']
topic = 'event'

[queue.income]
type = 'kafka'
broker = ['localhost:19092']
topic = ['push']
group = 'ws'

[login]
endpoint = 'http://localhost:3000/debug/login'
#event = 'login'

[logout]
endpoint = 'http://localhost:3000/debug/logout'
#event = 'login'

[assets]
path = 'gateway/assets'

[webhooks.history]
enable = false
endpoint = 'http://localhost:8000/v1/history'

[webhooks.echo]
enable = true
endpoint = 'http://localhost:3000/debug/echo'

[webhooks.render]
enable = true
endpoint = 'http://localhost:3000/debug/render/layout.json'

[[greet]]
enable = true
endpoint = 'http://localhost:3000/debug/render/layout.json'

[[greet]]
enable = true
path = 'user.json'

[[greet]]
enable = true
path = 'segment.tmpl.json'

