[application]

[web.app]

# HTML title tag content
title = "ui"

[web.watcher]
reload_html = true

[[web.proxy]]
backend = "http://localhost:3000/assets/apexcharts.min.js"
[[web.proxy]]
backend = "http://localhost:3000/assets/apexcharts.min.css"
[[web.proxy]]
backend = "http://localhost:3000/assets/mermaid.min.js"
