name: gateway

on:
  workflow_run:
    workflows: [ chef ]
    branches: [ release ]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fj0r/edap


jobs:
  build:

    runs-on: ubuntu-latest
    # if: ${{ startsWith(github.event.head_commit.message, '🏗️') }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: fj0r
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-edap
          restore-keys: |
            ${{ runner.os }}-buildx-edap

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:lastest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Delete untagged ghcr
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          # Personal access token (PAT) used to fetch the repository. The PAT is configured
          # with the local git config, which enables your scripts to run authenticated git
          # commands. The post-job step removes the PAT.
          # needs delete:packages permissions
          # required: true
          # [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
          token: ${{ secrets.GHCR_TOKEN }}
          # Repository name or  name with owner
          # Delete only from repository name
          # Default: ${{ github.repository }}
          repository: ${{ github.repository }}
          # 'The repository owner name'
          # Default: ${{ github.repository_owner }}
          repository_owner: ${{ github.repository_owner }}
          # 'The package names'
          # Delete only from comma separated package names
          # required: false
          package_name: ''
          # Delete only package versions without tag
          # required: false
          # Default: true
          # choices: true, false
          untagged_only: true
          # Except untagged multiplatform packages from deletion
          # only for untagged_only=true
          # needs docker installed
          except_untagged_multiplatform: false
          # the owner type
          # required: true
          # choices: org, user
          owner_type: user
